In [1]:
import numpy as np
import pandas as pd

### Yes24

In [2]:
# yes24
yes24 = pd.read_csv('./data/yes24.csv', encoding = 'cp949', index_col = False)
yes24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 957 entries, 0 to 956
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ISBN           957 non-null    int64
 1   book_name      957 non-null    object
 2   author         957 non-null    object
 3   price          957 non-null    int64
 4   star           573 non-null    float64
 5   category       957 non-null    object
 6   tag            488 non-null    object
 7   with_buy_book  867 non-null    object
 8   img            957 non-null    object
dtypes: float64(1), int64(2), object(6)
memory usage: 67.4+ KB

In [3]:
yes24 = yes24[yes24['ISBN'] != '0']

yes24['ISBN'] = yes24['ISBN'].astype(str)
yes24['star'] = yes24['star'].astype(str)

yes24.to_csv('./data/yes24.csv', encoding = 'cp949', sep = ',', index = False)
yes24.head(10)

,ISBN,book_name,author,price,star,category,tag,with_buy_book,img
0,9791155352014,몫,최은영 저/손은경 그림,6000,9.8,eBook>소설>한국소설,#북클럽에선무제한#룸펜레터에소개된책#작가를찾습니다_당신의작가를찾아보세요#성장#책읽아웃,"'밝은 밤', '애쓰지 않아도', '작별하지 않는다', '내게 무해한 사람', '여...",http://image.yes24.com/goods/87005231/XL
1,9791155352168,우리는 사랑했다 - 테이크아웃 05,강화길 저/키미앤일이 그림,6000,9.8,eBook>소설>한국소설,#작가를찾습니다_당신의작가를찾아보세요#2021한국문학의미래가될젊은작가#죽음에관하여,"'보건교사 안은영', '디디의 우산', '밤의 여행자들 - 오늘의 젊은 작가 3',...",http://image.yes24.com/goods/89869681/XL
2,9791169796569,스즈메의 문단속,신카이 마코토 저/민경욱 역,9100,10.0,eBook>소설>일본소설,#봄날엔로맨스#연애세포부활#아기다리고기다리던책,"'나미야 잡화점의 기적', '세상의 마지막 기차역', '오늘 밤, 세계에서 이 눈물...",http://image.yes24.com/goods/117721650/XL
3,9791198013033,김미경의 마흔 수업,김미경 저,12600,9.5,eBook>자기계발>처세술/삶의자세,#일타강사 #위로와응원#위로의말#마흔즈음에#인생지침서#인생선배#인생교훈,"'1퍼센트 부자의 법칙', '생각하라 그리고 부자가 되어라', '심플하게 산다', ...",http://image.yes24.com/goods/117474995/XL
4,9791197389467,1퍼센트 부자의 법칙,사이토 히토리 저/김진아 역,12000,8.0,eBook>자기계발>처세술/삶의자세,NaN,"'괜찮아, 분명 다 잘될 거야!', '생각하라 그리고 부자가 되어라', '네빌고다드...",http://image.yes24.com/goods/117310764/XL
5,9788900475005,입이 트이는 영어 2023년 3월호,이현석,8800,10.0,eBook>외국어>영어,NaN,"'입이 트이는 영어 2023년 2월호', '입이 트이는 영어 2023년 1월호', ...",http://image.yes24.com/goods/117748300/XL
6,9791188754618,브라질에 비가 내리면 스타벅스 주식을 사라,피터 나바로 저/이창식 역,12000,8.3,eBook>경제경영>투자/재테크,#북클럽에선무제한#주식투자입문#주식투자#주식심리학 #주식고수 #투자가이드 #똑똑하게...,"'부의 시나리오', '인플레이션에서 살아남기', '매매의 기술', '주식투자의 지혜...",http://image.yes24.com/goods/109322729/XL
7,9788997575619,원씽,"제이 파파산, 게리 켈러 저/구세희 역",10000,9.0,eBook>자기계발>성공학/경력관리,#성공하고싶다면#일하는방식#생활습관#국립중앙도서관사서추천,"'그릿(50만부 판매 기념 리커버 골드에디션)', '웰씽킹', '기브 앤 테이크',...",http://image.yes24.com/momo/TopCate0001/kepub/...
8,9791191521238,K 배터리 레볼루션,박순혁 저,13300,10.0,eBook>경제경영>경제,#미래전망#경제전망,"'돈의 심리학', '트렌드 코리아 2023', '챗GPT', '거인의 포트폴리오',...",http://image.yes24.com/goods/117612515/XL
9,9791190538527,만일 내가 인생을 다시 산다면 (10만 부 기념 스페셜 에디션),김혜남 저,12000,9.9,eBook>인문>심리/정신분석,#북클럽에선무제한#인생선배#인생2막대비#내인생이달라졌다#인생은끝까지모르는거야#인생교훈,"'내가 틀릴 수도 있습니다', '마음의 법칙', '클루지', '인스타 브레인', '...",http://image.yes24.com/goods/115211318/XL

In [4]:
yes24.tail()

,ISBN,book_name,author,price,star,category,tag,with_buy_book,img
952,9788937497285,어둠 속의 사건,오노레 드 발자크 저/이동렬 역,9800,nan,eBook>소설>프랑스소설,#세계문학,"'말 - 세계문학전집 189', '도둑 일기 - 세계문학전집 184', '앙리 브륄...",http://image.yes24.com/goods/112391425/XL
953,9791167960566,비전공자도 이해할 수 있는 AI 지식,박상길 저/정진호 그림,13000,9.0,eBook>자연과학>과학일반,#북클럽에선무제한#2022우수과학도서선정작#분철#책나눔위원회추천도서#미래과학#교양을...,"'이토록 뜻밖의 뇌과학', '어떻게 인간과 공존하는 인공지능을 만들 것인가', '다...",http://image.yes24.com/goods/112377342/XL
954,9788920044137,빅데이터의이해와활용,"이준환, 김용대, 이긍희, 원중호, 함유근 저",16000,10.0,eBook>대학교재>공학계열,NaN,"'통계학개론', '데이터베이스 시스템', '클라우드컴퓨팅', '파이썬과R', '데이...",http://image.yes24.com/goods/112326297/XL
955,9791161011943,2023 고종훈 한국사 서브노트,고종훈 저,12000,10.0,eBook>수험서>공무원,NaN,"'2023 고종훈 한국사 기출OX', '2022 고종훈 한국사 사료분석노트절대사료'...",http://image.yes24.com/goods/112228643/XL
956,9788942104918,기독교가 직면한 12가지 질문,레베카 맥클러플린 저 / 이여진 역,12600,nan,eBook>종교>기독교,NaN,"'팀 켈러의 탈기독교시대 전도', '메시지 S 스탠더드 에디션', '순전한 기독교'...",http://image.yes24.com/goods/112046472/XL

In [5]:
yes24.isna().sum()

ISBN               0
book_name          0
author             0
price              0
star               0
category           0
tag              469
with_buy_book     90
img                0
dtype: int64

### 교보문고

In [5]:
# 교보문고
kyobo = pd.read_csv('./data/kyobo.csv', encoding = 'cp949', index_col = False)
kyobo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ISBN       4620 non-null   object
 1   book_name  4620 non-null   object
 2   author     4620 non-null   object
 3   price      4620 non-null   int64
 4   star       4620 non-null   float64
 5   category   4620 non-null   object
 6   img        4620 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 252.8+ KB

In [6]:
kyobo.isna().sum()

ISBN         0
book_name    0
author       0
price        0
star         0
category     0
img          0
dtype: int64

In [7]:
kyobo['star'] = kyobo['star'].astype(str)
kyobo.head(3)

,ISBN,book_name,author,price,star,category,img
0,9788970000000,"[epub3.0]일러스트레이터, 그래픽디자인",이기섭,14400,10.0,eBook > IT/프로그래밍 > 그래픽/디자인,https://contents.kyobobook.co.kr/sih/fit-in/38...
1,9791190000000,진짜 쓰는 실무 엑셀,오빠두(전진권),13230,9.5,eBook > IT/프로그래밍 > OA (사무 보조 프로그램),https://contents.kyobobook.co.kr/sih/fit-in/38...
2,9791200000000,더 쉬운 자바 프로그래밍,최종명,19800,0.0,eBook > IT/프로그래밍 > 컴퓨터입문/활용,https://contents.kyobobook.co.kr/sih/fit-in/38...

### 네이버 시리즈

In [6]:
# 네이버 시리즈
naver_series = pd.read_csv('https://raw.githubusercontent.com/ebook-4/seyeon/master/book-trend-agent/outfile/naver_series_total.csv', 
                           sep = ',')
naver_series

,isbn,category,book_name,author,price,star,grade,img
0,9788937836374,소설,나미야 잡화점의 기적,히가시노 게이고,10000,9.4,전체 이용가,https://comicthumb-phinf.pstatic.net/20210919_...
1,9791169891912,소설,무명초,최서해,3000,8.0,전체 이용가,https://comicthumb-phinf.pstatic.net/20230307_...
2,9788951116445,예술/종교,성어거스틴의 고백록,"성 어거스틴, 선한용",16000,0.0,전체이용가,https://comicthumb-phinf.pstatic.net/20130910_...
3,9791197894978,소설,참지 않는 여자들,자일리 아마두 아말,10500,0.0,전체 이용가,https://comicthumb-phinf.pstatic.net/20230311_...
4,9791197894978,소설,참지 않는 여자들,자일리 아마두 아말,10500,0.0,전체 이용가,https://comicthumb-phinf.pstatic.net/20230311_...
...,...,...,...,...,...,...,...,...
42612,9791162243282,IT,유닉스의 탄생,브라이언 커니핸,16000,0.0,전체 이용가,https://comicthumb-phinf.pstatic.net/20210201_...
42613,9791165212490,IT,직장인을 위한 실무 데이터 분석 with 엑셀 (epub3),선양미,15400,0.0,전체 이용가,https://comicthumb-phinf.pstatic.net/20201118_...
42614,9791161340548,IT,핀란드를 게임 강국으로 만든 게임 기획자들,꼰쓰따 끌레메띠,10500,10.0,전체 이용가,https://comicthumb-phinf.pstatic.net/20200815_...
42615,9791161340371,IT,파이썬 핵심 개발자들과의 인터뷰,마이크 드리스콜,13000,0.0,전체 이용가,https://comicthumb-phinf.pstatic.net/20200814_...
42616,9791165212315,IT,자바 코딩의 기술 (epub3) (현장에서 뽑은 70가지 예제로 배우는 코드 잘 짜...,사이먼 하러.요르그 레너드.리누스 디에츠 지음,17600,0.0,전체 이용가,https://comicthumb-phinf.pstatic.net/20200805_...

In [7]:
naver_series.drop_duplicates(keep = 'first', inplace = True)

In [8]:
naver_series.rename(columns = {'isbn' : 'ISBN'}, inplace = True)
naver_series = naver_series[['ISBN', 'book_name', 'author', 'price', 'star', 'category', 'grade', 'img']]  # 칼럼 순서 변경

In [9]:
naver_series['ISBN'] = naver_series['ISBN'].astype(str)
naver_series['star'] = naver_series['star'].astype(str)
naver_series.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42370 entries, 0 to 42616
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ISBN       42370 non-null  object
 1   book_name  42370 non-null  object
 2   author     42369 non-null  object
 3   price      42370 non-null  int64
 4   star       42370 non-null  object
 5   category   42370 non-null  object
 6   grade      42347 non-null  object
 7   img        42370 non-null  object
dtypes: int64(1), object(7)
memory usage: 2.9+ MB

In [10]:
naver_series.to_csv('./data/naver_series_total.csv', encoding = 'utf-8', index = False)

In [11]:
naver_series = pd.read_csv('./data/naver_series_total.csv', encoding = 'utf-8', index_col = False)
naver_series.head(10)

,ISBN,book_name,author,price,star,category,grade,img
0,9788937836374,나미야 잡화점의 기적,히가시노 게이고,10000,9.4,소설,전체 이용가,https://comicthumb-phinf.pstatic.net/20210919_...
1,9791169891912,무명초,최서해,3000,8.0,소설,전체 이용가,https://comicthumb-phinf.pstatic.net/20230307_...
2,9788951116445,성어거스틴의 고백록,"성 어거스틴, 선한용",16000,0.0,예술/종교,전체이용가,https://comicthumb-phinf.pstatic.net/20130910_...
3,9791197894978,참지 않는 여자들,자일리 아마두 아말,10500,0.0,소설,전체 이용가,https://comicthumb-phinf.pstatic.net/20230311_...
4,9791190275811,플로라,소피 캐머런,9800,0.0,소설,전체 이용가,https://comicthumb-phinf.pstatic.net/20230311_...
5,9788954690973,"월 (wall, 최정나 장편소설)",최정나,10200,0.0,소설,전체 이용가,https://comicthumb-phinf.pstatic.net/20230310_...
6,9791159098413,낭패 (제9회 교보문고 스토리공모전 우수상 수상작),미아우,10300,10.0,소설,전체 이용가,https://comicthumb-phinf.pstatic.net/20230310_...
7,9791186317686,카르멘 (소설 카르멘에서 오페라 카르멘으로),프로스페르 메리메,12000,0.0,소설,전체 이용가,https://comicthumb-phinf.pstatic.net/20230310_...
8,9791164803040,무자비한 여자들 (최고의 쌍년을 찾아라),멜라니 블레이크,25000,0.0,소설,전체 이용가,https://comicthumb-phinf.pstatic.net/20230310_...
9,9788936438999,러브 몬스터,이두온,12800,0.0,소설,전체 이용가,https://comicthumb-phinf.pstatic.net/20230308_...

In [12]:
naver_series.isnull().sum()

ISBN          0
book_name     0
author        1
price         0
star          0
category      0
grade        23
img           0
dtype: int64

### 리디북스

In [13]:
# 리디북스
r100_1 = pd.read_csv('./data/리디100_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r100_2 = pd.read_csv('./data/리디100_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r100_3 = pd.read_csv('./data/리디100_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r100_4 = pd.read_csv('./data/리디100_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r110_1 = pd.read_csv('./data/리디110_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r110_2 = pd.read_csv('./data/리디110_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r110_3 = pd.read_csv('./data/리디110_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r110_4 = pd.read_csv('./data/리디110_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r200_1 = pd.read_csv('./data/리디200_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r200_2 = pd.read_csv('./data/리디200_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r200_3 = pd.read_csv('./data/리디200_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r200_4 = pd.read_csv('./data/리디200_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r300_1 = pd.read_csv('./data/리디300_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r300_2 = pd.read_csv('./data/리디300_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r300_3 = pd.read_csv('./data/리디300_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r300_4 = pd.read_csv('./data/리디300_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r400_1 = pd.read_csv('./data/리디400_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r400_2 = pd.read_csv('./data/리디400_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r400_3 = pd.read_csv('./data/리디400_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r400_4 = pd.read_csv('./data/리디400_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r500_1 = pd.read_csv('./data/리디500_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r500_2 = pd.read_csv('./data/리디500_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r500_3 = pd.read_csv('./data/리디500_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r500_4 = pd.read_csv('./data/리디500_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r600_1 = pd.read_csv('./data/리디600_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r600_2 = pd.read_csv('./data/리디600_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r600_3 = pd.read_csv('./data/리디600_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r600_4 = pd.read_csv('./data/리디600_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r700_1 = pd.read_csv('./data/리디700_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r700_2 = pd.read_csv('./data/리디700_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r700_3 = pd.read_csv('./data/리디700_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r700_4 = pd.read_csv('./data/리디700_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r800_1 = pd.read_csv('./data/리디800_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r800_2 = pd.read_csv('./data/리디800_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r800_3 = pd.read_csv('./data/리디800_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r800_4 = pd.read_csv('./data/리디800_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r1000_1 = pd.read_csv('./data/리디1000_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r1000_2 = pd.read_csv('./data/리디1000_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r1000_3 = pd.read_csv('./data/리디1000_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r1000_4 = pd.read_csv('./data/리디1000_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r1100_1 = pd.read_csv('./data/리디1100_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r1100_2 = pd.read_csv('./data/리디1100_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r1100_3 = pd.read_csv('./data/리디1100_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r1100_4 = pd.read_csv('./data/리디1100_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r1300_1 = pd.read_csv('./data/리디1300_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r1300_2 = pd.read_csv('./data/리디1300_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r1300_3 = pd.read_csv('./data/리디1300_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r1300_4 = pd.read_csv('./data/리디1300_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r1400_1 = pd.read_csv('./data/리디1400_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r1400_2 = pd.read_csv('./data/리디1400_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r1400_3 = pd.read_csv('./data/리디1400_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r1400_4 = pd.read_csv('./data/리디1400_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r1900_1 = pd.read_csv('./data/리디1900_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r1900_2 = pd.read_csv('./data/리디1900_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r1900_3 = pd.read_csv('./data/리디1900_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r1900_4 = pd.read_csv('./data/리디1900_4.csv', encoding = 'cp949', sep = ',', index_col = False)

r2200_1 = pd.read_csv('./data/리디2200_1.csv', encoding = 'cp949', sep = ',', index_col = False)
r2200_2 = pd.read_csv('./data/리디2200_2.csv', encoding = 'cp949', sep = ',', index_col = False)
r2200_3 = pd.read_csv('./data/리디2200_3.csv', encoding = 'cp949', sep = ',', index_col = False)
r2200_4 = pd.read_csv('./data/리디2200_4.csv', encoding = 'cp949', sep = ',', index_col = False)

In [14]:
ridi = pd.concat([r100_1, r100_2, r100_3, r100_4, r110_1, r110_2, r110_3, r110_4, r200_1, r200_2, r200_3, r200_4, 
                 r300_1, r300_2, r300_3, r300_4, r400_1, r400_2, r400_3, r400_4, r500_1, r500_2, r500_3, r500_4, 
                 r600_1, r600_2, r600_3, r600_4, r700_1, r700_2, r700_3, r700_4, r800_1, r800_2, r800_3, r800_4, 
                 r1000_1, r1000_2, r1000_3, r1000_4, r1100_1, r1100_2, r1100_3, r1100_4, r1300_1, r1300_2, r1300_3, r1300_4, 
                 r1400_1, r1400_2, r1400_3, r1400_4, r1900_1, r1900_2, r1900_3, r1900_4, r2200_1, r2200_2, r2200_3, r2200_4], axis = 0,
                ignore_index = True)
ridi

,Unnamed: 0,ISBN,book_name,author,price,star,category,book_image
0,0,9791169796569,스즈메의 문단속,신카이 마코토,"13,000",4.9점,소설,https://img.ridicdn.net/cover/754037469/xxlarge#1
1,1,9788956608594,구의 증명,최진영,"8,000",4.6점,소설,https://img.ridicdn.net/cover/754028617/xxlarge#1
2,2,9788936495701,아버지의 해방일지,정지아,"15,000",4.9점,소설,https://img.ridicdn.net/cover/754036090/xxlarge#1
3,3,9791156971610,지옥변,아쿠타가와 류노스케,500,4.7점,소설,https://img.ridicdn.net/cover/1189000235/xxlar...
4,4,9781781106303,개정 번역판 | 해리 포터와 마법사의 돌,조앤.K.롤링,"10,050",4.8점,소설,https://img.ridicdn.net/cover/3306000090/xxlar...
...,...,...,...,...,...,...,...,...
637,6,9788997924844,엔지니어를 위한 문장의 기술,아시야 고타,"16,000",0.0,컴퓨터/IT,https://img.ridicdn.net/cover/4281000027/xxlar...
638,7,9791162247303,왕초보 판매자도 파워셀러가 되는 네이버 스마트스토어 시작하기,서미진,"18,800",4점,컴퓨터/IT,https://img.ridicdn.net/cover/443000844/xxlarge#1
639,8,9788960882959,디지털 마케팅과 페이스북 광고,이민규,"15,000",0.0,컴퓨터/IT,https://img.ridicdn.net/cover/2856000057/xxlar...
640,9,9791163475675,Networkx를 활용한 네트워크 분석 기법 기초 입문,박건영,"8,000",5점,컴퓨터/IT,https://img.ridicdn.net/cover/1745003106/xxlar...
641,10,9791169216067,"피, 땀, 리셋",제이슨 슈라이어,"24,000",4.9점,컴퓨터/IT,https://img.ridicdn.net/cover/443001066/xxlarge#1

In [15]:
ridi.drop(['Unnamed: 0'], axis = 1, inplace = True)
ridi['price'] = ridi['price'].str.replace(',','')
ridi['price'] = ridi['price'].str.replace('원','')
ridi['price'] = ridi['price'].str.replace('%','')

ridi['star'] = ridi['star'].str.replace('점','')
ridi['star'] = ridi['star'].astype(str)
ridi.rename(columns = {'book_image' : 'img'}, inplace = True)

ridi['price'].fillna(0, inplace = True)
ridi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 642 entries, 0 to 641
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ISBN       642 non-null    object
 1   book_name  642 non-null    object
 2   author     642 non-null    object
 3   price      642 non-null    object
 4   star       642 non-null    object
 5   category   642 non-null    object
 6   img        642 non-null    object
dtypes: object(7)
memory usage: 35.2+ KB

In [16]:
ridi.isna().sum()

ISBN         0
book_name    0
author       0
price        0
star         0
category     0
img          0
dtype: int64

In [17]:
ridi.to_csv('./data/RIDIBooks.csv', encoding = 'cp949', sep = ',', index = False)

In [18]:
ridi = pd.read_csv('./data/RIDIBooks.csv', encoding = 'cp949', sep = ',', index_col = False)
ridi

,ISBN,book_name,author,price,star,category,img
0,9791169796569,스즈메의 문단속,신카이 마코토,13000,4.9,소설,https://img.ridicdn.net/cover/754037469/xxlarge#1
1,9788956608594,구의 증명,최진영,8000,4.6,소설,https://img.ridicdn.net/cover/754028617/xxlarge#1
2,9788936495701,아버지의 해방일지,정지아,15000,4.9,소설,https://img.ridicdn.net/cover/754036090/xxlarge#1
3,9791156971610,지옥변,아쿠타가와 류노스케,500,4.7,소설,https://img.ridicdn.net/cover/1189000235/xxlar...
4,9781781106303,개정 번역판 | 해리 포터와 마법사의 돌,조앤.K.롤링,10050,4.8,소설,https://img.ridicdn.net/cover/3306000090/xxlar...
...,...,...,...,...,...,...,...
637,9788997924844,엔지니어를 위한 문장의 기술,아시야 고타,16000,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/4281000027/xxlar...
638,9791162247303,왕초보 판매자도 파워셀러가 되는 네이버 스마트스토어 시작하기,서미진,18800,4.0,컴퓨터/IT,https://img.ridicdn.net/cover/443000844/xxlarge#1
639,9788960882959,디지털 마케팅과 페이스북 광고,이민규,15000,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/2856000057/xxlar...
640,9791163475675,Networkx를 활용한 네트워크 분석 기법 기초 입문,박건영,8000,5.0,컴퓨터/IT,https://img.ridicdn.net/cover/1745003106/xxlar...
641,9791169216067,"피, 땀, 리셋",제이슨 슈라이어,24000,4.9,컴퓨터/IT,https://img.ridicdn.net/cover/443001066/xxlarge#1

In [19]:
ridi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 642 entries, 0 to 641
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ISBN       642 non-null    object
 1   book_name  642 non-null    object
 2   author     642 non-null    object
 3   price      642 non-null    int64
 4   star       556 non-null    float64
 5   category   642 non-null    object
 6   img        642 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 35.2+ KB

### 통합 데이터 : Yes24 + 교보문고(생략) + 네이버 시리즈 + 리디북스

In [21]:
print(yes24.columns)
#print(kyobo.columns)
print(naver_series.columns)
print(ridi.columns)

Index(['ISBN', 'book_name', 'author', 'price', 'star', 'category', 'tag',
       'with_buy_book', 'img'],
      dtype='object')
Index(['ISBN', 'book_name', 'author', 'price', 'star', 'category', 'grade',
       'img'],
      dtype='object')
Index(['ISBN', 'book_name', 'author', 'price', 'star', 'category', 'img'], dtype='object')

In [22]:
yes24 = yes24.drop(['tag', 'with_buy_book'], axis = 1)
naver_series = naver_series.drop(['grade'], axis = 1)

total_book = pd.concat([yes24, naver_series, ridi], axis = 0, ignore_index = True)
total_book

,ISBN,book_name,author,price,star,category,img
0,9791155352014,몫,최은영 저/손은경 그림,6000,9.8,eBook>소설>한국소설,http://image.yes24.com/goods/87005231/XL
1,9791155352168,우리는 사랑했다 - 테이크아웃 05,강화길 저/키미앤일이 그림,6000,9.8,eBook>소설>한국소설,http://image.yes24.com/goods/89869681/XL
2,9791169796569,스즈메의 문단속,신카이 마코토 저/민경욱 역,9100,10.0,eBook>소설>일본소설,http://image.yes24.com/goods/117721650/XL
3,9791198013033,김미경의 마흔 수업,김미경 저,12600,9.5,eBook>자기계발>처세술/삶의자세,http://image.yes24.com/goods/117474995/XL
4,9791197389467,1퍼센트 부자의 법칙,사이토 히토리 저/김진아 역,12000,8.0,eBook>자기계발>처세술/삶의자세,http://image.yes24.com/goods/117310764/XL
...,...,...,...,...,...,...,...
43964,9788997924844,엔지니어를 위한 문장의 기술,아시야 고타,16000,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/4281000027/xxlar...
43965,9791162247303,왕초보 판매자도 파워셀러가 되는 네이버 스마트스토어 시작하기,서미진,18800,4.0,컴퓨터/IT,https://img.ridicdn.net/cover/443000844/xxlarge#1
43966,9788960882959,디지털 마케팅과 페이스북 광고,이민규,15000,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/2856000057/xxlar...
43967,9791163475675,Networkx를 활용한 네트워크 분석 기법 기초 입문,박건영,8000,5.0,컴퓨터/IT,https://img.ridicdn.net/cover/1745003106/xxlar...
43968,9791169216067,"피, 땀, 리셋",제이슨 슈라이어,24000,4.9,컴퓨터/IT,https://img.ridicdn.net/cover/443001066/xxlarge#1

In [23]:
total_book.head(10)

,ISBN,book_name,author,price,star,category,img
0,9791155352014,몫,최은영 저/손은경 그림,6000,9.8,eBook>소설>한국소설,http://image.yes24.com/goods/87005231/XL
1,9791155352168,우리는 사랑했다 - 테이크아웃 05,강화길 저/키미앤일이 그림,6000,9.8,eBook>소설>한국소설,http://image.yes24.com/goods/89869681/XL
2,9791169796569,스즈메의 문단속,신카이 마코토 저/민경욱 역,9100,10.0,eBook>소설>일본소설,http://image.yes24.com/goods/117721650/XL
3,9791198013033,김미경의 마흔 수업,김미경 저,12600,9.5,eBook>자기계발>처세술/삶의자세,http://image.yes24.com/goods/117474995/XL
4,9791197389467,1퍼센트 부자의 법칙,사이토 히토리 저/김진아 역,12000,8.0,eBook>자기계발>처세술/삶의자세,http://image.yes24.com/goods/117310764/XL
5,9788900475005,입이 트이는 영어 2023년 3월호,이현석,8800,10.0,eBook>외국어>영어,http://image.yes24.com/goods/117748300/XL
6,9791188754618,브라질에 비가 내리면 스타벅스 주식을 사라,피터 나바로 저/이창식 역,12000,8.3,eBook>경제경영>투자/재테크,http://image.yes24.com/goods/109322729/XL
7,9788997575619,원씽,"제이 파파산, 게리 켈러 저/구세희 역",10000,9.0,eBook>자기계발>성공학/경력관리,http://image.yes24.com/momo/TopCate0001/kepub/...
8,9791191521238,K 배터리 레볼루션,박순혁 저,13300,10.0,eBook>경제경영>경제,http://image.yes24.com/goods/117612515/XL
9,9791190538527,만일 내가 인생을 다시 산다면 (10만 부 기념 스페셜 에디션),김혜남 저,12000,9.9,eBook>인문>심리/정신분석,http://image.yes24.com/goods/115211318/XL

In [24]:
total_book.tail(10)

,ISBN,book_name,author,price,star,category,img
43959,9791197149894,데이터 분석가의 숫자유감,권정민,16000,4.5,컴퓨터/IT,https://img.ridicdn.net/cover/4547000005/xxlar...
43960,9791191600285,PM 인터뷰의 모든 것,게일 라크만 맥도웰,28000,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/852001126/xxlarge#1
43961,9791189610074,소프트웨어는 어떻게 밥벌이가 되었나,마틴 캠벨-켈리,18900,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/1575000009/xxlar...
43962,9788967821432,"한 달 만에 블로그 일 방문자 수 1,000명 만들기",권호영,3000,3.8,컴퓨터/IT,https://img.ridicdn.net/cover/4270000068/xxlar...
43963,9788920040627,4차 산업혁명과 공유가치창출 경영,백삼균,17000,0.0,경영/경제,https://img.ridicdn.net/cover/2709000803/xxlar...
43964,9788997924844,엔지니어를 위한 문장의 기술,아시야 고타,16000,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/4281000027/xxlar...
43965,9791162247303,왕초보 판매자도 파워셀러가 되는 네이버 스마트스토어 시작하기,서미진,18800,4.0,컴퓨터/IT,https://img.ridicdn.net/cover/443000844/xxlarge#1
43966,9788960882959,디지털 마케팅과 페이스북 광고,이민규,15000,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/2856000057/xxlar...
43967,9791163475675,Networkx를 활용한 네트워크 분석 기법 기초 입문,박건영,8000,5.0,컴퓨터/IT,https://img.ridicdn.net/cover/1745003106/xxlar...
43968,9791169216067,"피, 땀, 리셋",제이슨 슈라이어,24000,4.9,컴퓨터/IT,https://img.ridicdn.net/cover/443001066/xxlarge#1

In [25]:
total_book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43969 entries, 0 to 43968
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ISBN       43969 non-null  object
 1   book_name  43969 non-null  object
 2   author     43968 non-null  object
 3   price      43969 non-null  int64
 4   star       43883 non-null  object
 5   category   43969 non-null  object
 6   img        43969 non-null  object
dtypes: int64(1), object(6)
memory usage: 2.3+ MB

In [26]:
total_book.isna().sum()

ISBN          0
book_name     0
author        1
price         0
star         86
category      0
img           0
dtype: int64

In [27]:
total_book['star'].fillna(0, inplace = True)
total_book['author'].fillna('-', inplace = True)

In [28]:
total_book.isna().sum()

ISBN         0
book_name    0
author       0
price        0
star         0
category     0
img          0
dtype: int64

In [29]:
total_book.to_csv('./data/total_book.csv', encoding = 'utf-8-sig', sep = ',', index = False)

In [30]:
total_book = pd.read_csv('./data/total_book.csv', encoding = 'utf-8', sep = ',', index_col = False)
total_book.head(10)

,ISBN,book_name,author,price,star,category,img
0,9791155352014,몫,최은영 저/손은경 그림,6000,9.8,eBook>소설>한국소설,http://image.yes24.com/goods/87005231/XL
1,9791155352168,우리는 사랑했다 - 테이크아웃 05,강화길 저/키미앤일이 그림,6000,9.8,eBook>소설>한국소설,http://image.yes24.com/goods/89869681/XL
2,9791169796569,스즈메의 문단속,신카이 마코토 저/민경욱 역,9100,10.0,eBook>소설>일본소설,http://image.yes24.com/goods/117721650/XL
3,9791198013033,김미경의 마흔 수업,김미경 저,12600,9.5,eBook>자기계발>처세술/삶의자세,http://image.yes24.com/goods/117474995/XL
4,9791197389467,1퍼센트 부자의 법칙,사이토 히토리 저/김진아 역,12000,8.0,eBook>자기계발>처세술/삶의자세,http://image.yes24.com/goods/117310764/XL
5,9788900475005,입이 트이는 영어 2023년 3월호,이현석,8800,10.0,eBook>외국어>영어,http://image.yes24.com/goods/117748300/XL
6,9791188754618,브라질에 비가 내리면 스타벅스 주식을 사라,피터 나바로 저/이창식 역,12000,8.3,eBook>경제경영>투자/재테크,http://image.yes24.com/goods/109322729/XL
7,9788997575619,원씽,"제이 파파산, 게리 켈러 저/구세희 역",10000,9.0,eBook>자기계발>성공학/경력관리,http://image.yes24.com/momo/TopCate0001/kepub/...
8,9791191521238,K 배터리 레볼루션,박순혁 저,13300,10.0,eBook>경제경영>경제,http://image.yes24.com/goods/117612515/XL
9,9791190538527,만일 내가 인생을 다시 산다면 (10만 부 기념 스페셜 에디션),김혜남 저,12000,9.9,eBook>인문>심리/정신분석,http://image.yes24.com/goods/115211318/XL

In [31]:
total_book.tail(10)

,ISBN,book_name,author,price,star,category,img
43959,9791197149894,데이터 분석가의 숫자유감,권정민,16000,4.5,컴퓨터/IT,https://img.ridicdn.net/cover/4547000005/xxlar...
43960,9791191600285,PM 인터뷰의 모든 것,게일 라크만 맥도웰,28000,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/852001126/xxlarge#1
43961,9791189610074,소프트웨어는 어떻게 밥벌이가 되었나,마틴 캠벨-켈리,18900,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/1575000009/xxlar...
43962,9788967821432,"한 달 만에 블로그 일 방문자 수 1,000명 만들기",권호영,3000,3.8,컴퓨터/IT,https://img.ridicdn.net/cover/4270000068/xxlar...
43963,9788920040627,4차 산업혁명과 공유가치창출 경영,백삼균,17000,0.0,경영/경제,https://img.ridicdn.net/cover/2709000803/xxlar...
43964,9788997924844,엔지니어를 위한 문장의 기술,아시야 고타,16000,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/4281000027/xxlar...
43965,9791162247303,왕초보 판매자도 파워셀러가 되는 네이버 스마트스토어 시작하기,서미진,18800,4.0,컴퓨터/IT,https://img.ridicdn.net/cover/443000844/xxlarge#1
43966,9788960882959,디지털 마케팅과 페이스북 광고,이민규,15000,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/2856000057/xxlar...
43967,9791163475675,Networkx를 활용한 네트워크 분석 기법 기초 입문,박건영,8000,5.0,컴퓨터/IT,https://img.ridicdn.net/cover/1745003106/xxlar...
43968,9791169216067,"피, 땀, 리셋",제이슨 슈라이어,24000,4.9,컴퓨터/IT,https://img.ridicdn.net/cover/443001066/xxlarge#1

In [32]:
total_book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43969 entries, 0 to 43968
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ISBN       43969 non-null  object
 1   book_name  43969 non-null  object
 2   author     43969 non-null  object
 3   price      43969 non-null  int64
 4   star       43585 non-null  float64
 5   category   43969 non-null  object
 6   img        43969 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.3+ MB

In [33]:
total_book.isna().sum()

ISBN           0
book_name      0
author         0
price          0
star         384
category       0
img            0
dtype: int64

In [38]:
pd.read_csv('./data/total_book.csv', encoding = 'utf-8', sep = ',', index_col = False)

,ISBN,book_name,author,price,star,category,img
0,9791155352014,몫,최은영 저/손은경 그림,6000,9.8,eBook>소설>한국소설,http://image.yes24.com/goods/87005231/XL
1,9791155352168,우리는 사랑했다 - 테이크아웃 05,강화길 저/키미앤일이 그림,6000,9.8,eBook>소설>한국소설,http://image.yes24.com/goods/89869681/XL
2,9791169796569,스즈메의 문단속,신카이 마코토 저/민경욱 역,9100,10.0,eBook>소설>일본소설,http://image.yes24.com/goods/117721650/XL
3,9791198013033,김미경의 마흔 수업,김미경 저,12600,9.5,eBook>자기계발>처세술/삶의자세,http://image.yes24.com/goods/117474995/XL
4,9791197389467,1퍼센트 부자의 법칙,사이토 히토리 저/김진아 역,12000,8.0,eBook>자기계발>처세술/삶의자세,http://image.yes24.com/goods/117310764/XL
...,...,...,...,...,...,...,...
43964,9788997924844,엔지니어를 위한 문장의 기술,아시야 고타,16000,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/4281000027/xxlar...
43965,9791162247303,왕초보 판매자도 파워셀러가 되는 네이버 스마트스토어 시작하기,서미진,18800,4.0,컴퓨터/IT,https://img.ridicdn.net/cover/443000844/xxlarge#1
43966,9788960882959,디지털 마케팅과 페이스북 광고,이민규,15000,0.0,컴퓨터/IT,https://img.ridicdn.net/cover/2856000057/xxlar...
43967,9791163475675,Networkx를 활용한 네트워크 분석 기법 기초 입문,박건영,8000,5.0,컴퓨터/IT,https://img.ridicdn.net/cover/1745003106/xxlar...
43968,9791169216067,"피, 땀, 리셋",제이슨 슈라이어,24000,4.9,컴퓨터/IT,https://img.ridicdn.net/cover/443001066/xxlarge#1

In [39]:
pd.read_csv('./data/total_book.csv', encoding = 'utf-8', sep = ',', index_col = False).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43969 entries, 0 to 43968
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ISBN       43969 non-null  object
 1   book_name  43969 non-null  object
 2   author     43969 non-null  object
 3   price      43969 non-null  int64
 4   star       43969 non-null  float64
 5   category   43969 non-null  object
 6   img        43969 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.3+ MB

In [40]:
Ebook = total_book.drop(['author', 'price', 'star', 'category', 'img'], axis = 1)
Ebook.head()

            ISBN            book_name
0  9791155352014                    몫
1  9791155352168  우리는 사랑했다 - 테이크아웃 05
2  9791169796569             스즈메의 문단속
3  9791198013033           김미경의 마흔 수업
4  9791197389467          1퍼센트 부자의 법칙

In [41]:
Ebook.to_csv('./data/Ebook.csv', encoding = 'utf-8-sig', sep = ',', index = False)

In [46]:
Ebook_final = pd.read_csv('./data/Ebook.csv')
Ebook_final.head()

            ISBN            book_name
0  9791155352014                    몫
1  9791155352168  우리는 사랑했다 - 테이크아웃 05
2  9791169796569             스즈메의 문단속
3  9791198013033           김미경의 마흔 수업
4  9791197389467          1퍼센트 부자의 법칙

In [47]:
Ebook_final.duplicated().sum()

132

In [48]:
Ebook_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43969 entries, 0 to 43968
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ISBN       43969 non-null  object
 1   book_name  43969 non-null  object
dtypes: object(2)
memory usage: 687.1+ KB

In [49]:
Ebook_final = Ebook_final.drop_duplicates(['ISBN'], keep = 'first')
Ebook_final = Ebook_final.drop_duplicates(['book_name'], keep = 'first')
Ebook_final.head(20)

             ISBN                            book_name
0   9791155352014                                    몫
1   9791155352168                  우리는 사랑했다 - 테이크아웃 05
2   9791169796569                             스즈메의 문단속
3   9791198013033                           김미경의 마흔 수업
4   9791197389467                          1퍼센트 부자의 법칙
5   9788900475005                  입이 트이는 영어 2023년 3월호
6   9791188754618              브라질에 비가 내리면 스타벅스 주식을 사라
7   9788997575619                                   원씽
8   9791191521238                           K 배터리 레볼루션
9   9791190538527  만일 내가 인생을 다시 산다면 (10만 부 기념 스페셜 에디션)
10  9791161571195                              불편한 편의점
11  9788956608594                           구의 증명 [할인]
12  9788950910969                     이준석의 거부할 수 없는 미래
13  9791165347130                              세컨드 브레인
14  9791188331895                                돈의 속성
15  9788936495701                            아버지의 해방일지
16  9788959897100                         트렌드 코리아 2023
17  9791130697918               효기심의 권력으로 읽는 세계사 - 유럽편
18  9788901269665                       그들의 생각을 바꾸는 방법
19  9791187142690                         데일 카네기 인간관계론

In [50]:
Ebook_final.tail(20)

                ISBN                          book_name
43949  9788920023965                  Java프로그래밍(워크북 포함)
43950  9788968483226                    개정판 | 행복한 프로그래밍
43951  9791186805305                           마스터 알고리즘
43952  9791198036711           위대한 IT 영어 : Introduction
43953  9791140702497                그림으로 이해하는 가상화와 컨테이너
43954  9791140701032                        모두의 깃 & 깃허브
43955  9791140700813             개정판｜스프링 마이크로서비스 코딩 공작소
43956  9791163033868              개정판｜된다! 네이버 블로그 상위 노출
43957  9791165219888                  그림으로 이해하는 네트워크 용어
43958  9791197338250                           IT 사용설명서
43959  9791197149894                      데이터 분석가의 숫자유감
43960  9791191600285                       PM 인터뷰의 모든 것
43961  9791189610074                소프트웨어는 어떻게 밥벌이가 되었나
43962  9788967821432      한 달 만에 블로그 일 방문자 수 1,000명 만들기
43963  9788920040627                 4차 산업혁명과 공유가치창출 경영
43964  9788997924844                    엔지니어를 위한 문장의 기술
43965  9791162247303  왕초보 판매자도 파워셀러가 되는 네이버 스마트스토어 시작하기
43966  9788960882959                   디지털 마케팅과 페이스북 광고
43967  9791163475675     Networkx를 활용한 네트워크 분석 기법 기초 입문
43968  9791169216067                           피, 땀, 리셋

In [51]:
Ebook_final.duplicated().sum()

0

In [52]:
Ebook_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43326 entries, 0 to 43968
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ISBN       43326 non-null  object
 1   book_name  43326 non-null  object
dtypes: object(2)
memory usage: 1015.5+ KB

In [53]:
Ebook_final.to_csv('./data/Ebook_final.csv', encoding = 'utf-8-sig', sep = ',', index = False)

In [4]:
Ebook_final = pd.read_csv('./data/Ebook_final.csv', encoding='utf-8', sep=',', index_col=False)
Ebook_final = Ebook_final.drop_duplicates(['ISBN'], keep = 'first')
Ebook_final = Ebook_final.drop_duplicates(['title'], keep = 'first')
Ebook_final.head(20)

              ISBN                                title
0   9791155352014                                     몫
1   9791155352168                   우리는 사랑했다 - 테이크아웃 05
2   9791169796569                              스즈메의 문단속
3   9791198013033                            김미경의 마흔 수업
4   9791197389467                           1퍼센트 부자의 법칙
5   9788900475005                   입이 트이는 영어 2023년 3월호
6   9791188754618               브라질에 비가 내리면 스타벅스 주식을 사라
7   9788997575619                                    원씽
8   9791191521238                            K 배터리 레볼루션
9   9791190538527   만일 내가 인생을 다시 산다면 (10만 부 기념 스페셜 에디션)
10  9791161571195                               불편한 편의점
11  9788956608594                            구의 증명 [할인]
12  9788950910969                      이준석의 거부할 수 없는 미래
13  9791165347130                               세컨드 브레인
14  9791188331895                                 돈의 속성
15  9788936495701                             아버지의 해방일지
16  9788959897100                          트렌드 코리아 2023
17  9791130697918                효기심의 권력으로 읽는 세계사 - 유럽편
18  9788901269665                        그들의 생각을 바꾸는 방법
19  9791187142690                          데일 카네기 인간관계론

In [5]:
Ebook_final.duplicated().sum()

0

In [6]:
Ebook_final.to_csv('./data/Ebook_final.csv', encoding = 'utf-8-sig', sep = ',', index = False)

In [7]:
Ebook_final = pd.read_csv('./data/Ebook_final.csv', encoding = 'utf-8-sig', sep = ',', index_col = False)
Ebook_final.duplicated().sum()

0

In [9]:
Ebook_final = pd.read_csv('./data/Ebook_final.csv', encoding = 'utf-8-sig', sep = ',', index_col = False)
Ebook_final['author'] = Ebook_final['author'].str.replace('"', "'")
Ebook_final

,ISBN,title,author,price,star,category,img
0,9791155352014,몫,최은영 저/손은경 그림,6000,9.8,eBook>소설>한국소설,http://image.yes24.com/goods/87005231/XL
1,9791155352168,우리는사랑했다-테이크아웃05,강화길 저/키미앤일이 그림,6000,9.8,eBook>소설>한국소설,http://image.yes24.com/goods/89869681/XL
2,9791169796569,스즈메의문단속,신카이 마코토 저/민경욱 역,9100,10.0,eBook>소설>일본소설,http://image.yes24.com/goods/117721650/XL
3,9791198013033,김미경의마흔수업,김미경 저,12600,9.5,eBook>자기계발>처세술/삶의자세,http://image.yes24.com/goods/117474995/XL
4,9791197389467,1퍼센트부자의법칙,사이토 히토리 저/김진아 역,12000,8.0,eBook>자기계발>처세술/삶의자세,http://image.yes24.com/goods/117310764/XL
...,...,...,...,...,...,...,...
115839,9791197345739,이젠2000년생이다,허두영,9900,0.0,자기계발,https://cover.millie.co.kr/service/cover/1795...
115840,9791165211998,만원으로일주일반찬만들기,송혜영,9900,0.0,라이프스타일,https://cover.millie.co.kr/service/cover/1795...
115841,9791188474011,잘되는사람,소진영,9900,0.0,자기계발,https://cover.millie.co.kr/service/cover/1794...
115842,9791169290425,달의여신루나와그림자아저씨,거리 / 그림: 박은경,9900,0.0,어린이·청소년,https://cover.millie.co.kr/service/cover/1795...
115843,9788901170930,나는티타임에탐닉한다,이민숙,9900,0.0,라이프스타일,https://cover.millie.co.kr/service/cover/1431...

In [10]:
Ebook_final.to_csv('./data/Ebook_final.csv', encoding = 'utf-8-sig', sep = ',', index = False)

In [11]:
Ebook_final['title'] = Ebook_final['title'].str.replace('"', "'")
Ebook_final

,ISBN,title,author,price,star,category,img
0,9791155352014,몫,최은영 저/손은경 그림,6000,9.8,eBook>소설>한국소설,http://image.yes24.com/goods/87005231/XL
1,9791155352168,우리는사랑했다-테이크아웃05,강화길 저/키미앤일이 그림,6000,9.8,eBook>소설>한국소설,http://image.yes24.com/goods/89869681/XL
2,9791169796569,스즈메의문단속,신카이 마코토 저/민경욱 역,9100,10.0,eBook>소설>일본소설,http://image.yes24.com/goods/117721650/XL
3,9791198013033,김미경의마흔수업,김미경 저,12600,9.5,eBook>자기계발>처세술/삶의자세,http://image.yes24.com/goods/117474995/XL
4,9791197389467,1퍼센트부자의법칙,사이토 히토리 저/김진아 역,12000,8.0,eBook>자기계발>처세술/삶의자세,http://image.yes24.com/goods/117310764/XL
...,...,...,...,...,...,...,...
115839,9791197345739,이젠2000년생이다,허두영,9900,0.0,자기계발,https://cover.millie.co.kr/service/cover/1795...
115840,9791165211998,만원으로일주일반찬만들기,송혜영,9900,0.0,라이프스타일,https://cover.millie.co.kr/service/cover/1795...
115841,9791188474011,잘되는사람,소진영,9900,0.0,자기계발,https://cover.millie.co.kr/service/cover/1794...
115842,9791169290425,달의여신루나와그림자아저씨,거리 / 그림: 박은경,9900,0.0,어린이·청소년,https://cover.millie.co.kr/service/cover/1795...
115843,9788901170930,나는티타임에탐닉한다,이민숙,9900,0.0,라이프스타일,https://cover.millie.co.kr/service/cover/1431...

In [12]:
Ebook_final.to_csv('./data/Ebook_final.csv', encoding = 'utf-8-sig', sep = ',', index = False)

In [3]:
Ebook = pd.read_csv('./data/Ebook_final_v3.csv', encoding='utf-8-sig', sep=',', index_col=False)
Ebook.to_csv('./data/Ebook_final_v3.csv', encoding='utf-8-sig', sep=',', index=False)

In [4]:
Ebook = pd.read_csv('./data/Ebook_final_v3.csv', encoding='utf-8-sig', sep=',', index_col=False)
Ebook

,ISBN,title,author,price,star,category,img
0,9791188808090,매일10분최빈출영단어의기적(체험판)(영어표현이잡히고생활영어가된다!),JAMES M.VARDAMAN,0,0.0,어학,https://comicthumb-phinf.pstatic.net/20181107_...
1,9791196261283,외로워서배고픈사람들의식탁(체험판)(여성과이방인의정체성으로본프랑스),곽미성,0,0.0,인문,https://comicthumb-phinf.pstatic.net/20180724_...
2,9791191383133,지식을공유하라(한국오픈액세스운동),권범철,0,0.0,사회,https://comicthumb-phinf.pstatic.net/20220518_...
3,9791190259866,솔직히퇴사후회하죠?(체험판)(공기업을퇴사하고자발적백수가된서른살의이야기),김민태,0,0.0,시/에세이,https://comicthumb-phinf.pstatic.net/20210909_...
4,9791159099427,고시맨(체험판),김펑,0,0.0,소설,https://comicthumb-phinf.pstatic.net/20181005_...
...,...,...,...,...,...,...,...
114754,9788950980221,레오나르도다빈치,월터 아이작슨,54400,10.0,인문,https://comicthumb-phinf.pstatic.net/20190424_...
114755,9788952774224,"중세1(야만인,그리스도교도,이슬람교도의시대,476-1000)",움베르토 에코,56000,10.0,역사/문화,https://comicthumb-phinf.pstatic.net/20190110_...
114756,9781781105177,해리포터컴플리트컬렉션:HarryPotter:TheCompleteCollection(...,J.K.,63300,10.0,eBook > 외국도서 > 문학,https://contents.kyobobook.co.kr/sih/fit-in/38...
114757,9791159555886,중환자의학4판,대한중환자의학회,70000,10.0,과학,https://comicthumb-phinf.pstatic.net/20200805_...
114758,9788967356132,삼국지세트(전6권),나관중,75600,10.0,역사/문화,https://comicthumb-phinf.pstatic.net/20190912_...